
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: AaAa123!
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: v1

#    sentinel:
#      transport:
#        dashboard: localhost:8080

mybatis:
  type-aliases-package: com.ray.domain.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

#project:
#  name: user-center
#ahas:
#  license: 6e8711d703d64b2f8e9641e3b210d2c2
#  namespace: default
