spring:
  application:
    name: content-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content-center?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: AaAa123!
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: v1
          target-version: v1
    sentinel:
      transport:
        dashboard: localhost:8080
#      打开/关闭掉springMVC端点的保护
      filter:
        enabled: true

  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.ray.domain.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#logging:
#  level:
#    com:
#      ray:
#        content_center:
#          feignclient:
#            UserCenterFeignClient: debug
#feign:
#  client:
#    config:
#      #全局配置
#     default:
#       loggerLevel: full
#  httpclient:
##     让feign使用apache httpclient做请求；而不是默认的urlconnection
#     enabled: true
##     feign的最大连接数
#     max-connections: 200
##     feign单个路径的最大连接数
#     max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'
#resttemplate:
#  sentinel:
#    enabled: false
#feign:
#  sentinel:
#    enabled: true
#project:
#  name: content-center
#ahas:
#  license: 6e8711d703d64b2f8e9641e3b210d2c2
#  namespace: default
