
spring:
  application:
    name: content-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content-center?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: AaAa123!
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: v1
          target-version: v1
mybatis:
  type-aliases-package: com.ray.domain.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
